### ISSUE TITLE
recommend using demodb for demos

### ISSUE THREAD

**Issue by clach04** [iancr01/Ingres-Dot-Net-Examples#1]
https://github.com/iancr01/Ingres-Dot-Net-Examples/blob/38fb61571a4b73dd9f1d45bbb2d7f0b89d1da573/Connections/IngresConnection_SampleCode.cs#L11

Alternative is to pick up from an environment variable, e.g. see https://github.com/ActianCorp/OpenROAD_json/blob/master/csharp/JsonRPCdemo.cs#L12

Either way I would default to demodb if you can :-)

**Comment by iancr01** [comment]
Fixed in a couple of places... Waiting to see if it needs to be changed anywhere else...
